### ISSUE TITLE
🐛 Bug: Broken Links for OSPO Guides

### ISSUE THREAD

**Issue by alldo-dev** [todogroup/ospodefinition.org#27]
**Describe the bug**
There are a couple of links in the README file

**To Reproduce**

1. Go to [README](https://github.com/todogroup/ospodefinition.org/blob/main/README.md)
2. Click on [How to Create an Open Source Program](https://todogroup.org/resources/guides/create-program)
3. Redirects to 404 page in the TODO website.

1. Go to [README](https://github.com/todogroup/ospodefinition.org/blob/main/README.md)
2. Click on [Measuring Your Open Source Program](https://todogroup.org/resources/guides/measuring)
3. Redirects to 404 page in the TODO website.

1. Go to [README](https://github.com/todogroup/ospodefinition.org/blob/main/README.md)
2. Click on [Tools for Managing Your Open Source Program](https://todogroup.org/resources/guides/management-tools)
3. Redirects to 404 page in the TODO website.

**Expected behavior**
Each hyperlink redirects to the acual page

**Comment by MarkusTiede** [comment]
Are there any plans on fixing this?

**Comment by alldo-dev** [comment]
[PR25](https://github.com/todogroup/ospodefinition.org/pull/25) waiting for review
