### ISSUE TITLE
Survey not for open source projects

### ISSUE THREAD

**Issue by gmajan** [todogroup/ospodefinition.org#5]
Hi,
Thank you for sending through the survey. Great initiative. We are so happy with the focus on open source challenges.
We are an open source project under the Linux Foundation too. So I do not think we fit the profile your want to survey.
We are happy to share our experiences working with public sector engagement with open source (national govs and international organisations like UN and World Bank.)
Looking forward to reviewing the results of your survey.

**Comment by caniszczyk** [comment]
@gmajan you can always email me caniszczyk@linuxfoundation.org to meet and catch up on this topic

We have a new OSPO Landscape here: https://landscape.todogroup.org
